<?php
/**
 *@file
 *Interfax pbc module written at home
 */
/**
 * Inmpementing hook_menu().
 */
function interfaxpbc_menu() {
 $items['admin/config/interfaxpbc'] = array(
  'title' => 'InterfaxPBC',
  'description' => 'Interfax Pbc description here',
  'page callback' => 'drupal_get_form',
  'page arguments' => array('interfaxpbc_page'),
  'access callback' => 'user_access',
  'access arguments' => array('access content'),
 );
 return $items;
}
/**
 * Implementinh hook_help. Adding module link to help page and help information.
 */
function interfaxpbc_help($path, $arg) {
  switch ($path) {
     case 'admin/help#interfaxpbc':
        return '<p>' . t('Interfaxpbc help informations') . '</p>';
     case 'admin/config/interfaxpbc':
      return '<p>' . t('Page help information .. module help ?') . '</p>';
  }
}
function interfaxpbc_page($form, &$form_state) {

$form['interfaxpbc_username'] = array(
  '#type' => 'textfield',
  '#title' => t('Username'),
  '#description' => 'Your InterFAX User',
  '#default_value' => variable_get('interfaxpbc_username'),
  '#required' => TRUE,
  );

$form['interfaxpbc_password'] = array(
  '#type' => 'password',
  '#title' => t('Password'),
  '#description' => 'Your InterFAX Password',
  '#default_value' => variable_get('interfaxpbc_password'),
  '#required' => TRUE,
  );

$form['interfaxpbc_method'] = array(
  '#type' => 'select',
  '#title' => t('Select Method to Use'),
  '#description' => t('Interfax method used description'),
  '#options' => array(
    'text' => 'Text Selected',
    'html' => 'Html Selected',
    'json' => 'Json Selected',
    ),
  );
return system_settings_form($form);
}
